// THIS FILE IS AUTOMATICALLY GENERATED BY ts-auto-index.
export type { API } from './API';
export type { PostId, PostSimpleView, PostDetailView } from './posts';
export type { UserId, UserSimpleView, UserDetailView, UserAuthorizedView, UserIdMainGet, UserIdMainRoutes, UserIdPostsGet, UserIdPostsRoutes, UserIdRoutes, UserMainGet, UserMainPostError, UserMainPost, UserMainRoutes, UserRoutes, UserMeGet, UserMePatch, UserMeRoutes, UserNicknameMainGet, UserNicknameMainRoutes, UserNicknameRoutes, UserSlugMainGet, UserSlugMainRoutes, UserSlugRoutes } from './users';
