services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    volumes:
      - ./scripts/localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
      - localstack:/var/lib/localstack
volumes:
  localstack:
    driver: local
