version: '3'

tasks:
  init:
    desc: Initialize all packages
    cmds:
      - sh ./scripts/init.sh

  install:
    desc: Install all packages
    cmds:
      - sh ./scripts/for-each-package.sh npm install

  build:
    desc: Build all packages
    cmds:
      - sh ./scripts/for-each-package.sh npm run build

  test:
    desc: Test all packages
    cmds:
      - sh ./scripts/for-each-package.sh npm test

  all:
    desc: Run install, build, and test
    deps:
      - init
      - test
