import { globSync } from "glob";
import { readFileSync, writeFileSync } from "node:fs";

const packages = globSync("../../../*/*/*/package.json", {
  absolute: true,
}).sort();
const nodes = packages.map((p) => {
  const json = JSON.parse(readFileSync(p).toString());
  const dependencies = Object.keys(json.dependencies ?? {})
    .concat(Object.keys(json.devDependencies ?? {}))
    .filter((d) => d.startsWith("@this-project/"))
    .map((d) => {
      const [, a] = d.match(/^@this-project\/(.*)$/)!;
      return a;
    });
  const [, a] = json.name.match(/^@this-project\/(.*)$/)!;
  const name = a;
  const [, b, c, d] = p
    .replace(/\\/g, "/")
    .match(/^.*\/([^\/]*)\/([^\/]*)\/([^\/]*)\/([^\/]*)$/)!;
  const path = `packages/${b}/${c}/${d}`;
  return {
    name,
    path,
    dependencies,
  };
});

const output = nodes.map(
  (n) => `  build-${n.name}:
    desc: Build ${n.path}
    deps: [${n.dependencies.map((d) => `build-${d}`).join(", ")}]
    cmds:
      - yarn workspace @this-project/${n.name} build
    run: once
`
);

writeFileSync(
  "../../../../task/init.yml",
  `# This file is generated by generate-task-init-yml. Do not edit it directly.

version: '3'

tasks:
  init:
    desc: Initialize all packages
    cmds:
      - yarn install
      - task: build
    run: once
  build:
    desc: Build all packages
    deps: [${nodes.map((n) => `build-${n.name}`).join(", ")}]
    run: once

${output.join("")}`
);
