// THIS FILE IS AUTOMATICALLY GENERATED BY ts-auto-index.
export type { ObjectId, ObjectStorageAdapter } from './objectStorage';
export type { TransactionManager, TransactionAdapter } from './transaction';
